config/routes.rb
Rails.application.routes.draw do
  

  resources :logs
  mount Ckeditor::Engine => '/ckeditor'
  resources :meetings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users , :controllers => { 
  	:registrations => "users/registrations"
  }
  resources :projects do
    resources :meetings
    resources :logs
  end
  resources :clients
  resources :colleagues
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root to: "home#index"
end

app/views/share/footer.html.erb
<!-- Footer -->
			<div id="footer">

				<!-- Copyright -->
					<ul class="copyright">
						<li>&copy; P. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li><li>Deverlop: <a href="mailto:pattiyaa@gmail.com">Pattiya Akaratawee</a></li>
					</ul>

			</div>

app/views/share/header.html.erb
<!-- Header -->
			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<%= render template: "/share/signin"%>
						</div>

					<%= render :template=> 'share/menu'%>

				</div>

				<div class="bottom">

					<!-- Social Icons -->
						<ul class="icons">
							<% if user_signed_in? && !current_user.blank? %>
							<li>
							<%= link_to destroy_user_session_path  do %>
								<i class="fa fa-sign-out" aria-hidden="true"></i>
							<%end%>
							</li>
							<% end %>
						</ul>

				</div>

			</div>

app/views/share/menu.html.erb
<!-- Nav -->
<nav id="nav">
<!--

	Prologue's nav expects links in one of two formats:

	1. Hash link (scrolls to a different section within the page)

	   <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

	2. Standard link (sends the user to another page/site)

	   <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

	-->
	<ul>
	    <%= nav_link t('menu.home'), root_path(:anchor => 'top') ,'icon fa-home','top-link' %>
	    <%= nav_link t('menu.workflow'), root_path(:anchor => 'workflow') ,'icon fa-bullseye','workflow-link'  %>
	    <%= nav_link t('menu.projects'),projects_path ,'icon fa-th','projects-link','projects'  %>
	    <%= nav_link t('menu.colleague'),colleagues_path ,'icon fa-users','colleagues-link','colleagues' %>
	    <%= nav_link t('menu.customers'), clients_path,'icon fa-user-secret','customers-link','clients' %>
	

	</ul>
</nav>

app/views/share/signin.html.erb
<% if user_signed_in? && !current_user.blank? %>


<span class="image avatar48">
    <%= link_to edit_user_registration_path, :class=>"avatar48" do%>
	<div class="user profile" style="background-image:url('<%= current_user.image.url if current_user.image.present?%>')"></div>
	<%end%>
</span>


<h1 id="title"><%=  current_user.name %></h1>
<p><%=  current_user.title %></p>
<% else %>
<%= link_to  new_user_session_path ,data: { modal: true} do%>
	<span class=""><i class="fa fa-user fa-3x"></i></span>
	<h1 id="title"><%=t(:signin)%></h1>
<%end%>
<% end %>