config/routes.rb
Rails.application.routes.draw do
  

  resources :logs
  mount Ckeditor::Engine => '/ckeditor'
  resources :meetings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users , :controllers => { 
  	:registrations => "users/registrations"
  }
  resources :projects do
    resources :meetings
    resources :logs
  end
  resources :clients
  resources :colleagues
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root to: "home#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :logperson ,class_name: 'User', foreign_key: 'logger_id'
  has_and_belongs_to_many :users
  belongs_to :project
end

app/controllers/meetings_controller.rb
class MeetingsController < InheritedResources::Base
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  def new
    @meeting = Meeting.new
    if isforproject
    	@meeting.project_id = params[:project_id]
      @attendeeslist = attendeeslist
	end
    @meeting.logperson = current_user
    @meeting.meetingdate = Date.today
  end
  def edit
    @isforproject = isforproject 
    @attendeeslist = attendeeslist
  end

  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        if isforproject   
          format.html { redirect_to project_path(project_id,:anchor => 'meeting') , notice: 'Meeting was successfully created.' }
        else
          format.html { redirect_to @metting, notice: 'Meeting was successfully created.' }
        end
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        if isforproject  
          format.html { redirect_to project_path(project_id,:anchor => 'meeting') , notice: 'Meeting was successfully created.' }
        else
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @meeting.destroy
    respond_to do |format|
      if isforproject 
      format.html { redirect_to project_path(project_id,:anchor => 'meeting') , notice: 'Meeting was successfully destroyed.' } 
      else
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end
  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end
    def meeting_params

      params.require(:meeting).permit(:meetingdate, :title, :data, :logger_id, :project_id,  {:user_ids => []})
    end
    def isforproject
    	params[:project_id].present? || params[:meeting][:project_id].present?
    end
    def project_id
      
      if params[:meeting].present?
       params[:meeting][:project_id]
      else
        params[:project_id]
      end
    end
    def attendeeslist
      
      project = Project.find(project_id)
      list=[]
      list = list.push([project.projectmanager.name,project.projectmanager.id])
      project.users.pluck(:name, :id).each do |user|
          list.push(user)
      end
      return  list
    end
    def resolve_layout
      case action_name
      when "show"
        "modal"
      else
        "application"
      end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= semantic_form_for @meeting do |f| %>
  <%= f.inputs do %>
    <%= f.input :project %>
    <%= f.input :meetingdate,:as => :date_picker, label: 'Date' %>
     <%= f.input :users,as: :select,:input_html => { :multiple => true }, label: 'Attendees',:collection => attendeeslist%>
    <%= f.input :title %>
    <%= f.input :data , :as => :ckeditor,input_html: {:ckeditor => {:toolbar => 'mini'}}%>
    <%= f.input :logperson, label: 'Log person' %>
    
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/meetings/_list.html.erb
<div class="table-responsive">
<table class="table table-hover table-sm">


  <tbody>
    <% meetings.each do |meeting| %>
      <tr>
        <td class="col-sm-4"><small><%= meeting.meetingdate.strftime(t('date.formats.default')) if meeting.meetingdate.present? %></small></td>
       
        <td class="col-sm-8">
          <div class="meeting inlist">
            <h4 ><%= meeting.title %></h4>
           <!--  <%= meeting.data.html_safe %> -->
            <p><small> 
              <strong> Log person: </strong> 
              <%= meeting.logperson.name if  meeting.logperson.present?%> <br/>
              <strong>Attendee: </strong>
              <% meeting.users.each do |user| %>
                <br/> &nbsp<%= user.name %> 
                <% end%>
            </small></p>
            
            <div class="pull-right">
              <%= link_to 'Show', project_meeting_path(project_id: @project.id, id: meeting.id ),data: { modal: true} %>
               <% if meeting.logperson.present? && meeting.logperson == current_user %>
                <%= link_to 'Edit', edit_project_meeting_path(project_id: @project.id,id: meeting.id) %>
                <%= link_to 'Destroy', project_meeting_path(project_id: @project.id, id: meeting.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%>
              
            </div>
          </div>
        </td>
  
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/meetings/edit.html.erb
<div class="container mt-3">
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting ,  attendeeslist: @attendeeslist %>

<%= link_to 'Back', @isforproject ?   project_path(@meeting.project.id,:anchor => 'meeting') : meetings_path%>
</div>

app/views/meetings/index.html.erb
<div class="container mt-3">
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Meetingdate</th>
      <th>Title</th>
      <th>Data</th>
      <th>Log person</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.meetingdate.strftime(t('date.formats.default')) if meeting.meetingdate.present? %></td>
        <td><%= meeting.title %></td>
        <td><%= meeting.data %></td>
        <td><%= meeting.logperson.name if meeting.logperson.present? %></td>
        <td><%= meeting.project.name if meeting.project.present? %></td>
        <td> 
          <div><%= link_to 'Show', meeting %></div>
          <div><%= link_to 'Edit', edit_meeting_path(meeting) %></div>
          <div><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>
</div>

app/views/meetings/new.html.erb
<div class="container mt-3">
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting , attendeeslist: @attendeeslist %>

<%= link_to 'Back', meetings_path %>
</div>

app/views/meetings/show.html.erb
<% content_for :title,  @meeting.title  %>

<div>
  <small>
    <strong>Date:</strong>
    <%= @meeting.meetingdate.strftime(t('date.formats.default'))  if @meeting.meetingdate.present?  %>
  </small>
</div>
<div>
  <small>
    <strong>Logger:</strong>
    <%= @meeting.logperson.name if @meeting.logperson.present? %>
  </small>
</div>




<strong>Log data:</strong>
<div class="container">
  <small>
    <%= @meeting.data.html_safe %>
  </small>
</div>