config/routes.rb
Rails.application.routes.draw do
  

  resources :logs
  mount Ckeditor::Engine => '/ckeditor'
  resources :meetings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users , :controllers => { 
  	:registrations => "users/registrations"
  }
  resources :projects do
    resources :meetings
    resources :logs
  end
  resources :clients
  resources :colleagues
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root to: "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :projectmanager, class_name: 'User', foreign_key: 'projectmanager_id'
  belongs_to :client
  has_and_belongs_to_many :users
  has_many :meetings
  has_many :logs
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    
    @projects = Project.where(projectmanager: current_user.id)
    
    # @paticipatedprojects = Project.includes(:users).where(users: {id: current_user}, active: true)
    @paticipatedprojects =  Project.find(Project.includes(:users).where(users: {id: current_user}, active: true).ids)

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.projectmanager = current_user
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :detail, :start_date, :end_date, :active, :seq, :projectmanager_id, :client_id, {:user_ids => []})
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= semantic_form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
  <%= f.input :seq %>
  <%= f.input :name %>
  <%= f.input :detail, input_html:{ rows: '5'} %>
  <%= f.input :active,as: :toggleswitch, label: 'Active'%>
  <%= f.input :start_date, :as => :date_picker %>
  <%= f.input :end_date, :as => :date_picker %>
  <%= f.input :client_id,as: :select, label: 'Customer',:collection => Client.pluck(:name, :id),:prompt => "Please select" %>
  <%= f.input :projectmanager_id,as: :select, label: 'Project manager',:collection => User.pluck(:name, :id),:prompt => "Please select" %>
  <%= f.input :user_ids,as: :select,:input_html => { :multiple => true }, label: 'Members',:collection => User.pluck(:name, :id)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_list.html.erb
<div class="row ">
      <% projects.each do |project| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card project">
          <div class=" card-block">
            <h4 class="card-title"><%= link_to project.name, project %> <% if project.active == false%>(Inactive)<%end%></h4>
            <p class="card-text"><%= project.detail %><br/>
              <small class="text-muted">
              Start date: &nbsp <%= project.start_date.strftime(t('date.formats.default'))  %><br/>
              End date: &nbsp <%= project.end_date.strftime(t('date.formats.default'))  %><br/>
              Customer: &nbsp <%= project.client.name if project.client.present? %><br/>
              Location: &nbsp <%= project.client.address if project.client.present? %><br/>
              <% if project.projectmanager != current_user %>
              Project manager: <%= project.projectmanager.name%><br/>
              <%end%>
              Members: <% project.users.each do |u| %>
                        <%= u.name%> <br/>
                        <%end%>
            </small>
            </p>
          </div>
          <% if project.projectmanager == current_user %>
          <div class="card-block">
            <%= link_to 'Edit', edit_project_path(project) %> &nbsp
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
          <%end%>
        </div>
      </div>
      <% end %>
    </div>

app/views/projects/edit.html.erb
<div class="container mt-3">
<h2>Editing Project</h2>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<section id="projects" class="three">
  <div class="container">
    <header>
      <h2>Projects</h2>
    </header>
    <h4>Managed projects </h4>
    <div class="row pull-right" ><%= link_to 'New Project', new_project_path, :class => 'btn btn-secondary' %></div>
    <%= render 'projects/list', :projects => @projects  %>
    
  </div>
</section>
<section id="projects" class="two">
  <div class="container">
    <h4>Paticipated projects </h4>
    <%= render 'projects/list', :projects => @paticipatedprojects  %>
  </div>
</section>

app/views/projects/new.html.erb
<div class="container mt-3">
<h2>New Project</h2>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="container mt-3 headertitle">
  <p id="notice"><%= notice %></p>
  <header>
  <% if @project.projectmanager == current_user %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %>
  <% end%>
    <div class="content">
      <h2>
        <%= @project.name %>
      </h2>
      <p>
        <%= @project.detail %>
      </p>
    </div>
    <div class="row small">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div>
          <strong>Duration:</strong>  
          <%= @project.start_date.strftime(t('date.formats.default')) %> to <%= @project.end_date.strftime(t('date.formats.default'))  %>
         
        </div>
        <div>
          <strong>Project manager:</strong> <%= @project.projectmanager.name if @project.projectmanager.present?%>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div><strong>Client:</strong> <%= @project.client.name if @project.client.present? %> </div>
        <div><strong>Location:</strong> <%= @project.client.address if @project.client.present? %></div> 
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div><strong>Contact person:</strong>
          <%= @project.client.contactperson if @project.client.present? %>
        </div> 
        <div><strong>Telephone:</strong>
          <%= @project.client.telephone if @project.client.present? %>

        </div> 
        <div><strong>email:</strong>
          <%= @project.client.email if @project.client.present? %>
        </div>
      </div>
    </div>
  </header>
  <div class="three">
    <h2>Members</h2>
    <%= render  'colleagues/list'  ,colleagues: @project.users%>
  </div>
</div>
<section id="meeting" class="two">
    <div class="container">
    <h4>Meeting</h4> <div class="pull-right"> <%= link_to 'new meeting',new_project_meeting_path(project_id: @project.id)  %></div>
    <%= render   'meetings/list'  ,meetings: @project.meetings %>
    </div>
</section>
<section id="log" class="three">
  <div class="container">
    <h4>Log</h4> <div class="pull-right"> <%= link_to 'new log',new_project_log_path(project_id: @project.id)  %></div>
    <%= render   'logs/list'  ,logs: @project.logs %>
  </div>
</section>