config/routes.rb
Rails.application.routes.draw do
  

  resources :logs
  mount Ckeditor::Engine => '/ckeditor'
  resources :meetings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users , :controllers => { 
  	:registrations => "users/registrations"
  }
  resources :projects do
    resources :meetings
    resources :logs
  end
  resources :clients
  resources :colleagues
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root to: "home#index"
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :logperson,class_name: 'User'
  belongs_to :project
  has_many :pictures, :class_name => "Ckeditor::Picture",:as => "assetable"
  
end

app/controllers/logs_controller.rb
class LogsController < InheritedResources::Base
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  def new
    @log = Log.new
    if isforproject
    	@log.project_id = params[:project_id]
	  end
    @log.logperson = current_user
    @log.logdate = Time.now
  end
  def edit
    @isforproject = isforproject 
   
  end
  def create
    @log = Log.new(log_params)
    respond_to do |format|
      if @log.save
        updatepicture
        if isforproject   
          format.html { redirect_to project_path(project_id,:anchor => 'log') , notice: 'Log was successfully created.' }
        else
          format.html { redirect_to @log, notice: 'Log was successfully created.' }
        end
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @log.update(log_params)
        updatepicture
        if isforproject  
          format.html { redirect_to project_path(project_id,:anchor => 'log') , notice: 'Log was successfully created.' }
        else
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @log.destroy
    respond_to do |format|
      if isforproject 
      format.html { redirect_to project_path(project_id,:anchor => 'log') , notice: 'Log was successfully destroyed.' } 
      else
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end
  private
    def set_log
      @log = Log.find(params[:id])
    end
    def log_params
      params.require(:log).permit(:logdate, :data, :logperson_id, :project_id, :pictures)
    end
    def isforproject
    	params[:project_id].present? || params[:log][:project_id].present?
    end
    def project_id
      
      if params[:log].present?
       params[:log][:project_id]
      else
        params[:project_id]
      end
    end
    def pictures
      params[:log][:pictures]
    end
    def updatepicture
      @pics=[]
      if pictures.present?
        pictures.each do |pic|
          begin
            if eval(pic)[:id].present?
              @pics.push(Ckeditor::Picture.find(eval(pic)[:id]))
            end
          rescue
            @pics.push(Ckeditor::Picture.new(data: pic))
          end
        end
        @log.pictures = @pics 
        @log.save
      end
    end
    def resolve_layout
      case action_name
      when "show"
        "modal"
      else
        "application"
      end
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= semantic_form_for @log do |f| %>
  <%= f.inputs do %>
    <%= f.input :logdate, :as => :datetime_picker  %>
    <%= f.input :data , :as => :ckeditor ,input_html: {:ckeditor => {:toolbar => 'mini'}}%>
    <%= f.input :logperson %>
    <%= f.input :project %>
    <%= f.input  :pictures, :as => :filesupload,:image_preview=> true %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/logs/_list.html.erb
<div class="table-responsive ">
<table class="table table-hover table-sm">
  

  <tbody>
    <% logs.each do |log| %>
      <tr>
        <td class="col-sm-3">
        <div>
          <span class="image avatar48">
              <%= link_to edit_user_registration_path, :class=>"avatar48" do%>
            <div class="user profile" style="background-image:url('<%= log.logperson.image.url if log.logperson.image.present?%>')"></div>
            <%end%>
          </span>
          <h1 id="title"><%=  log.logperson.name %></h1>
          <p><small><%=  log.logperson.title %></small><br/>
             <small><small><%= log.logdate.strftime(t('time.formats.default')) if log.logdate.present? %></small></small>
          </p>
        </div> 
       
        </td>
       
        <td class="col-sm-9">
          <div class="log inlist ">
           
            <%= log.data.html_safe %> 
            
            <div class="thumb">
        
              <% log.pictures.each do |pic| %>
              <%= cl_image_tag(pic.url, :crop=>"thumb")%>
              <% end%>
            </div>
            <div class="pull-right">
              <%= link_to 'Show', project_log_path(project_id: @project.id, id: log.id ),data: { modal: true} %>
               <% if log.logperson.present? && log.logperson == current_user %>
                <%= link_to 'Edit', edit_project_log_path(project_id: @project.id,id: log.id) %>
                <%= link_to 'Destroy', project_log_path(project_id: @project.id, id: log.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%>
              
            </div>
          </div>
        </td>
  
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/logs/edit.html.erb
<div class="container mt-3">
<h1>Editing Log</h1>

<%= render 'form', log: @log %>


<%= link_to 'Back', @isforproject ?   project_path(@log.project.id,:anchor => 'log') : logs_path%>
</div>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logs</h1>

<table>
  <thead>
    <tr>
      <th>Logdate</th>
      <th>Data</th>
      <th>Logperson</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.logdate %></td>
        <td><%= log.data %></td>
        <td><%= log.logperson %></td>
        <td><%= log.project %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<div class="container mt-3">
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>
</div>

app/views/logs/show.html.erb
<% content_for :title do %>

<span class="image avatar48">
	<div class="user profile" style="background-image:url('<%= @log.logperson.image.url if @log.logperson.image.present?%>')"></div>
</span>
<%=  @log.logperson.name if @log.logperson.present?  %><br/>
<%= @log.logdate.strftime(t('time.formats.default')) %>
<% end%>

<p>
  <%= @log.data.html_safe %>
</p>
<div>
<% @log.pictures.each do |p|%>
  <div class="image fit">
	<%= image_tag p.url%>
  </div>
<%end%>
</div>